//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCS.DIS.Presenter.RetrieveService.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Diagnose", Namespace="http://schemas.datacontract.org/2004/07/RCS.DIS.Services.DTOs")]
    [System.SerializableAttribute()]
    public partial class Diagnose : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BestandsdatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiagnoseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PeildatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialismeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Bestandsdatum {
            get {
                return this.BestandsdatumField;
            }
            set {
                if ((this.BestandsdatumField.Equals(value) != true)) {
                    this.BestandsdatumField = value;
                    this.RaisePropertyChanged("Bestandsdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiagnoseCode {
            get {
                return this.DiagnoseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnoseCodeField, value) != true)) {
                    this.DiagnoseCodeField = value;
                    this.RaisePropertyChanged("DiagnoseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Omschrijving {
            get {
                return this.OmschrijvingField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingField, value) != true)) {
                    this.OmschrijvingField = value;
                    this.RaisePropertyChanged("Omschrijving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Peildatum {
            get {
                return this.PeildatumField;
            }
            set {
                if ((this.PeildatumField.Equals(value) != true)) {
                    this.PeildatumField = value;
                    this.RaisePropertyChanged("Peildatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialismeCode {
            get {
                return this.SpecialismeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialismeCodeField, value) != true)) {
                    this.SpecialismeCodeField = value;
                    this.RaisePropertyChanged("SpecialismeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Versie {
            get {
                return this.VersieField;
            }
            set {
                if ((object.ReferenceEquals(this.VersieField, value) != true)) {
                    this.VersieField = value;
                    this.RaisePropertyChanged("Versie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Specialisme", Namespace="http://schemas.datacontract.org/2004/07/RCS.DIS.Services.DTOs")]
    [System.SerializableAttribute()]
    public partial class Specialisme : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BestandsdatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PeildatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialismeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Bestandsdatum {
            get {
                return this.BestandsdatumField;
            }
            set {
                if ((this.BestandsdatumField.Equals(value) != true)) {
                    this.BestandsdatumField = value;
                    this.RaisePropertyChanged("Bestandsdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Omschrijving {
            get {
                return this.OmschrijvingField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingField, value) != true)) {
                    this.OmschrijvingField = value;
                    this.RaisePropertyChanged("Omschrijving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Peildatum {
            get {
                return this.PeildatumField;
            }
            set {
                if ((this.PeildatumField.Equals(value) != true)) {
                    this.PeildatumField = value;
                    this.RaisePropertyChanged("Peildatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialismeCode {
            get {
                return this.SpecialismeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialismeCodeField, value) != true)) {
                    this.SpecialismeCodeField = value;
                    this.RaisePropertyChanged("SpecialismeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Versie {
            get {
                return this.VersieField;
            }
            set {
                if ((object.ReferenceEquals(this.VersieField, value) != true)) {
                    this.VersieField = value;
                    this.RaisePropertyChanged("Versie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zorgactiviteit", Namespace="http://schemas.datacontract.org/2004/07/RCS.DIS.Services.DTOs")]
    [System.SerializableAttribute()]
    public partial class Zorgactiviteit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BestandsdatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PeildatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZorgactiviteitCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZorgprofielklasseCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Bestandsdatum {
            get {
                return this.BestandsdatumField;
            }
            set {
                if ((this.BestandsdatumField.Equals(value) != true)) {
                    this.BestandsdatumField = value;
                    this.RaisePropertyChanged("Bestandsdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Omschrijving {
            get {
                return this.OmschrijvingField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingField, value) != true)) {
                    this.OmschrijvingField = value;
                    this.RaisePropertyChanged("Omschrijving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Peildatum {
            get {
                return this.PeildatumField;
            }
            set {
                if ((this.PeildatumField.Equals(value) != true)) {
                    this.PeildatumField = value;
                    this.RaisePropertyChanged("Peildatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Versie {
            get {
                return this.VersieField;
            }
            set {
                if ((object.ReferenceEquals(this.VersieField, value) != true)) {
                    this.VersieField = value;
                    this.RaisePropertyChanged("Versie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZorgactiviteitCode {
            get {
                return this.ZorgactiviteitCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZorgactiviteitCodeField, value) != true)) {
                    this.ZorgactiviteitCodeField = value;
                    this.RaisePropertyChanged("ZorgactiviteitCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZorgprofielklasseCode {
            get {
                return this.ZorgprofielklasseCodeField;
            }
            set {
                if ((this.ZorgprofielklasseCodeField.Equals(value) != true)) {
                    this.ZorgprofielklasseCodeField = value;
                    this.RaisePropertyChanged("ZorgprofielklasseCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zorgproduct", Namespace="http://schemas.datacontract.org/2004/07/RCS.DIS.Services.DTOs")]
    [System.SerializableAttribute()]
    public partial class Zorgproduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BestandsdatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclaratiecodeOnverzekerdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeclaratiecodeVerzekerdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvingConsumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OmschrijvingLatijnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PeildatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZorgproductCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Bestandsdatum {
            get {
                return this.BestandsdatumField;
            }
            set {
                if ((this.BestandsdatumField.Equals(value) != true)) {
                    this.BestandsdatumField = value;
                    this.RaisePropertyChanged("Bestandsdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeclaratiecodeOnverzekerd {
            get {
                return this.DeclaratiecodeOnverzekerdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclaratiecodeOnverzekerdField, value) != true)) {
                    this.DeclaratiecodeOnverzekerdField = value;
                    this.RaisePropertyChanged("DeclaratiecodeOnverzekerd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeclaratiecodeVerzekerd {
            get {
                return this.DeclaratiecodeVerzekerdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeclaratiecodeVerzekerdField, value) != true)) {
                    this.DeclaratiecodeVerzekerdField = value;
                    this.RaisePropertyChanged("DeclaratiecodeVerzekerd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OmschrijvingConsument {
            get {
                return this.OmschrijvingConsumentField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingConsumentField, value) != true)) {
                    this.OmschrijvingConsumentField = value;
                    this.RaisePropertyChanged("OmschrijvingConsument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OmschrijvingLatijn {
            get {
                return this.OmschrijvingLatijnField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingLatijnField, value) != true)) {
                    this.OmschrijvingLatijnField = value;
                    this.RaisePropertyChanged("OmschrijvingLatijn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Peildatum {
            get {
                return this.PeildatumField;
            }
            set {
                if ((this.PeildatumField.Equals(value) != true)) {
                    this.PeildatumField = value;
                    this.RaisePropertyChanged("Peildatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Versie {
            get {
                return this.VersieField;
            }
            set {
                if ((object.ReferenceEquals(this.VersieField, value) != true)) {
                    this.VersieField = value;
                    this.RaisePropertyChanged("Versie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZorgproductCode {
            get {
                return this.ZorgproductCodeField;
            }
            set {
                if ((this.ZorgproductCodeField.Equals(value) != true)) {
                    this.ZorgproductCodeField = value;
                    this.RaisePropertyChanged("ZorgproductCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbcOverzicht", Namespace="http://schemas.datacontract.org/2004/07/RCS.DIS.Services.DTOs")]
    [System.SerializableAttribute()]
    public partial class DbcOverzicht : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BestandsdatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiagnoseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short JaarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatientenPerDiagnoseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatientenPerSpecialismeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatientenPerZorgproductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PeildatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialismeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubtrajectenPerDiagnoseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubtrajectenPerSpecialismeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubtrajectenPerZorgproductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VerkoopprijsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZorgproductCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Bestandsdatum {
            get {
                return this.BestandsdatumField;
            }
            set {
                if ((this.BestandsdatumField.Equals(value) != true)) {
                    this.BestandsdatumField = value;
                    this.RaisePropertyChanged("Bestandsdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiagnoseCode {
            get {
                return this.DiagnoseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnoseCodeField, value) != true)) {
                    this.DiagnoseCodeField = value;
                    this.RaisePropertyChanged("DiagnoseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Jaar {
            get {
                return this.JaarField;
            }
            set {
                if ((this.JaarField.Equals(value) != true)) {
                    this.JaarField = value;
                    this.RaisePropertyChanged("Jaar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientenPerDiagnose {
            get {
                return this.PatientenPerDiagnoseField;
            }
            set {
                if ((this.PatientenPerDiagnoseField.Equals(value) != true)) {
                    this.PatientenPerDiagnoseField = value;
                    this.RaisePropertyChanged("PatientenPerDiagnose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientenPerSpecialisme {
            get {
                return this.PatientenPerSpecialismeField;
            }
            set {
                if ((this.PatientenPerSpecialismeField.Equals(value) != true)) {
                    this.PatientenPerSpecialismeField = value;
                    this.RaisePropertyChanged("PatientenPerSpecialisme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientenPerZorgproduct {
            get {
                return this.PatientenPerZorgproductField;
            }
            set {
                if ((this.PatientenPerZorgproductField.Equals(value) != true)) {
                    this.PatientenPerZorgproductField = value;
                    this.RaisePropertyChanged("PatientenPerZorgproduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Peildatum {
            get {
                return this.PeildatumField;
            }
            set {
                if ((this.PeildatumField.Equals(value) != true)) {
                    this.PeildatumField = value;
                    this.RaisePropertyChanged("Peildatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialismeCode {
            get {
                return this.SpecialismeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialismeCodeField, value) != true)) {
                    this.SpecialismeCodeField = value;
                    this.RaisePropertyChanged("SpecialismeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubtrajectenPerDiagnose {
            get {
                return this.SubtrajectenPerDiagnoseField;
            }
            set {
                if ((this.SubtrajectenPerDiagnoseField.Equals(value) != true)) {
                    this.SubtrajectenPerDiagnoseField = value;
                    this.RaisePropertyChanged("SubtrajectenPerDiagnose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubtrajectenPerSpecialisme {
            get {
                return this.SubtrajectenPerSpecialismeField;
            }
            set {
                if ((this.SubtrajectenPerSpecialismeField.Equals(value) != true)) {
                    this.SubtrajectenPerSpecialismeField = value;
                    this.RaisePropertyChanged("SubtrajectenPerSpecialisme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubtrajectenPerZorgproduct {
            get {
                return this.SubtrajectenPerZorgproductField;
            }
            set {
                if ((this.SubtrajectenPerZorgproductField.Equals(value) != true)) {
                    this.SubtrajectenPerZorgproductField = value;
                    this.RaisePropertyChanged("SubtrajectenPerZorgproduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Verkoopprijs {
            get {
                return this.VerkoopprijsField;
            }
            set {
                if ((this.VerkoopprijsField.Equals(value) != true)) {
                    this.VerkoopprijsField = value;
                    this.RaisePropertyChanged("Verkoopprijs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Versie {
            get {
                return this.VersieField;
            }
            set {
                if ((object.ReferenceEquals(this.VersieField, value) != true)) {
                    this.VersieField = value;
                    this.RaisePropertyChanged("Versie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZorgproductCode {
            get {
                return this.ZorgproductCodeField;
            }
            set {
                if ((this.ZorgproductCodeField.Equals(value) != true)) {
                    this.ZorgproductCodeField = value;
                    this.RaisePropertyChanged("ZorgproductCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbcProfiel", Namespace="http://schemas.datacontract.org/2004/07/RCS.DIS.Services.DTOs")]
    [System.SerializableAttribute()]
    public partial class DbcProfiel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BestandsdatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiagnoseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short JaarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PatientenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PeildatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialismeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubtrajectenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZorgactiviteitCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZorgactiviteitenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZorgproductCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Bestandsdatum {
            get {
                return this.BestandsdatumField;
            }
            set {
                if ((this.BestandsdatumField.Equals(value) != true)) {
                    this.BestandsdatumField = value;
                    this.RaisePropertyChanged("Bestandsdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiagnoseCode {
            get {
                return this.DiagnoseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnoseCodeField, value) != true)) {
                    this.DiagnoseCodeField = value;
                    this.RaisePropertyChanged("DiagnoseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Jaar {
            get {
                return this.JaarField;
            }
            set {
                if ((this.JaarField.Equals(value) != true)) {
                    this.JaarField = value;
                    this.RaisePropertyChanged("Jaar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Patienten {
            get {
                return this.PatientenField;
            }
            set {
                if ((this.PatientenField.Equals(value) != true)) {
                    this.PatientenField = value;
                    this.RaisePropertyChanged("Patienten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Peildatum {
            get {
                return this.PeildatumField;
            }
            set {
                if ((this.PeildatumField.Equals(value) != true)) {
                    this.PeildatumField = value;
                    this.RaisePropertyChanged("Peildatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialismeCode {
            get {
                return this.SpecialismeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialismeCodeField, value) != true)) {
                    this.SpecialismeCodeField = value;
                    this.RaisePropertyChanged("SpecialismeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Subtrajecten {
            get {
                return this.SubtrajectenField;
            }
            set {
                if ((this.SubtrajectenField.Equals(value) != true)) {
                    this.SubtrajectenField = value;
                    this.RaisePropertyChanged("Subtrajecten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Versie {
            get {
                return this.VersieField;
            }
            set {
                if ((object.ReferenceEquals(this.VersieField, value) != true)) {
                    this.VersieField = value;
                    this.RaisePropertyChanged("Versie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZorgactiviteitCode {
            get {
                return this.ZorgactiviteitCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZorgactiviteitCodeField, value) != true)) {
                    this.ZorgactiviteitCodeField = value;
                    this.RaisePropertyChanged("ZorgactiviteitCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Zorgactiviteiten {
            get {
                return this.ZorgactiviteitenField;
            }
            set {
                if ((this.ZorgactiviteitenField.Equals(value) != true)) {
                    this.ZorgactiviteitenField = value;
                    this.RaisePropertyChanged("Zorgactiviteiten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZorgproductCode {
            get {
                return this.ZorgproductCodeField;
            }
            set {
                if ((this.ZorgproductCodeField.Equals(value) != true)) {
                    this.ZorgproductCodeField = value;
                    this.RaisePropertyChanged("ZorgproductCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRetrieveService")]
    public interface IRetrieveService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/Jaren", ReplyAction="http://tempuri.org/IRetrieveService/JarenResponse")]
        short[] Jaren();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/Jaren", ReplyAction="http://tempuri.org/IRetrieveService/JarenResponse")]
        System.Threading.Tasks.Task<short[]> JarenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/Versies", ReplyAction="http://tempuri.org/IRetrieveService/VersiesResponse")]
        string[] Versies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/Versies", ReplyAction="http://tempuri.org/IRetrieveService/VersiesResponse")]
        System.Threading.Tasks.Task<string[]> VersiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/DiagnoseOmschrijvingContainsNumber", ReplyAction="http://tempuri.org/IRetrieveService/DiagnoseOmschrijvingContainsNumberResponse")]
        int DiagnoseOmschrijvingContainsNumber(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/DiagnoseOmschrijvingContainsNumber", ReplyAction="http://tempuri.org/IRetrieveService/DiagnoseOmschrijvingContainsNumberResponse")]
        System.Threading.Tasks.Task<int> DiagnoseOmschrijvingContainsNumberAsync(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/DiagnoseOmschrijvingContainsEntities", ReplyAction="http://tempuri.org/IRetrieveService/DiagnoseOmschrijvingContainsEntitiesResponse")]
        RCS.DIS.Presenter.RetrieveService.ServiceReference.Diagnose[] DiagnoseOmschrijvingContainsEntities(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/DiagnoseOmschrijvingContainsEntities", ReplyAction="http://tempuri.org/IRetrieveService/DiagnoseOmschrijvingContainsEntitiesResponse")]
        System.Threading.Tasks.Task<RCS.DIS.Presenter.RetrieveService.ServiceReference.Diagnose[]> DiagnoseOmschrijvingContainsEntitiesAsync(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/SpecialismeOmschrijvingContainsNumber", ReplyAction="http://tempuri.org/IRetrieveService/SpecialismeOmschrijvingContainsNumberResponse" +
            "")]
        int SpecialismeOmschrijvingContainsNumber(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/SpecialismeOmschrijvingContainsNumber", ReplyAction="http://tempuri.org/IRetrieveService/SpecialismeOmschrijvingContainsNumberResponse" +
            "")]
        System.Threading.Tasks.Task<int> SpecialismeOmschrijvingContainsNumberAsync(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/SpecialismeOmschrijvingContainsEntities", ReplyAction="http://tempuri.org/IRetrieveService/SpecialismeOmschrijvingContainsEntitiesRespon" +
            "se")]
        RCS.DIS.Presenter.RetrieveService.ServiceReference.Specialisme[] SpecialismeOmschrijvingContainsEntities(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/SpecialismeOmschrijvingContainsEntities", ReplyAction="http://tempuri.org/IRetrieveService/SpecialismeOmschrijvingContainsEntitiesRespon" +
            "se")]
        System.Threading.Tasks.Task<RCS.DIS.Presenter.RetrieveService.ServiceReference.Specialisme[]> SpecialismeOmschrijvingContainsEntitiesAsync(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/ZorgactiviteitOmschrijvingContainsNumber", ReplyAction="http://tempuri.org/IRetrieveService/ZorgactiviteitOmschrijvingContainsNumberRespo" +
            "nse")]
        int ZorgactiviteitOmschrijvingContainsNumber(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/ZorgactiviteitOmschrijvingContainsNumber", ReplyAction="http://tempuri.org/IRetrieveService/ZorgactiviteitOmschrijvingContainsNumberRespo" +
            "nse")]
        System.Threading.Tasks.Task<int> ZorgactiviteitOmschrijvingContainsNumberAsync(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/ZorgactiviteitOmschrijvingContainsEntities", ReplyAction="http://tempuri.org/IRetrieveService/ZorgactiviteitOmschrijvingContainsEntitiesRes" +
            "ponse")]
        RCS.DIS.Presenter.RetrieveService.ServiceReference.Zorgactiviteit[] ZorgactiviteitOmschrijvingContainsEntities(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/ZorgactiviteitOmschrijvingContainsEntities", ReplyAction="http://tempuri.org/IRetrieveService/ZorgactiviteitOmschrijvingContainsEntitiesRes" +
            "ponse")]
        System.Threading.Tasks.Task<RCS.DIS.Presenter.RetrieveService.ServiceReference.Zorgactiviteit[]> ZorgactiviteitOmschrijvingContainsEntitiesAsync(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/ZorgproductOmschrijvingContainsNumber", ReplyAction="http://tempuri.org/IRetrieveService/ZorgproductOmschrijvingContainsNumberResponse" +
            "")]
        int ZorgproductOmschrijvingContainsNumber(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/ZorgproductOmschrijvingContainsNumber", ReplyAction="http://tempuri.org/IRetrieveService/ZorgproductOmschrijvingContainsNumberResponse" +
            "")]
        System.Threading.Tasks.Task<int> ZorgproductOmschrijvingContainsNumberAsync(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/ZorgproductOmschrijvingContainsEntities", ReplyAction="http://tempuri.org/IRetrieveService/ZorgproductOmschrijvingContainsEntitiesRespon" +
            "se")]
        RCS.DIS.Presenter.RetrieveService.ServiceReference.Zorgproduct[] ZorgproductOmschrijvingContainsEntities(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/ZorgproductOmschrijvingContainsEntities", ReplyAction="http://tempuri.org/IRetrieveService/ZorgproductOmschrijvingContainsEntitiesRespon" +
            "se")]
        System.Threading.Tasks.Task<RCS.DIS.Presenter.RetrieveService.ServiceReference.Zorgproduct[]> ZorgproductOmschrijvingContainsEntitiesAsync(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/DbcOverzichtNumber", ReplyAction="http://tempuri.org/IRetrieveService/DbcOverzichtNumberResponse")]
        int DbcOverzichtNumber(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string versie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/DbcOverzichtNumber", ReplyAction="http://tempuri.org/IRetrieveService/DbcOverzichtNumberResponse")]
        System.Threading.Tasks.Task<int> DbcOverzichtNumberAsync(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string versie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/DbcOverzichtEntities", ReplyAction="http://tempuri.org/IRetrieveService/DbcOverzichtEntitiesResponse")]
        RCS.DIS.Presenter.RetrieveService.ServiceReference.DbcOverzicht[] DbcOverzichtEntities(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string versie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/DbcOverzichtEntities", ReplyAction="http://tempuri.org/IRetrieveService/DbcOverzichtEntitiesResponse")]
        System.Threading.Tasks.Task<RCS.DIS.Presenter.RetrieveService.ServiceReference.DbcOverzicht[]> DbcOverzichtEntitiesAsync(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string versie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/DbcProfielNumber", ReplyAction="http://tempuri.org/IRetrieveService/DbcProfielNumberResponse")]
        int DbcProfielNumber(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string zorgactiviteitCode, string versie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/DbcProfielNumber", ReplyAction="http://tempuri.org/IRetrieveService/DbcProfielNumberResponse")]
        System.Threading.Tasks.Task<int> DbcProfielNumberAsync(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string zorgactiviteitCode, string versie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/DbcProfielEntities", ReplyAction="http://tempuri.org/IRetrieveService/DbcProfielEntitiesResponse")]
        RCS.DIS.Presenter.RetrieveService.ServiceReference.DbcProfiel[] DbcProfielEntities(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string zorgactiviteitCode, string versie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetrieveService/DbcProfielEntities", ReplyAction="http://tempuri.org/IRetrieveService/DbcProfielEntitiesResponse")]
        System.Threading.Tasks.Task<RCS.DIS.Presenter.RetrieveService.ServiceReference.DbcProfiel[]> DbcProfielEntitiesAsync(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string zorgactiviteitCode, string versie);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRetrieveServiceChannel : RCS.DIS.Presenter.RetrieveService.ServiceReference.IRetrieveService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveServiceClient : System.ServiceModel.ClientBase<RCS.DIS.Presenter.RetrieveService.ServiceReference.IRetrieveService>, RCS.DIS.Presenter.RetrieveService.ServiceReference.IRetrieveService {
        
        public RetrieveServiceClient() {
        }
        
        public RetrieveServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetrieveServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetrieveServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetrieveServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public short[] Jaren() {
            return base.Channel.Jaren();
        }
        
        public System.Threading.Tasks.Task<short[]> JarenAsync() {
            return base.Channel.JarenAsync();
        }
        
        public string[] Versies() {
            return base.Channel.Versies();
        }
        
        public System.Threading.Tasks.Task<string[]> VersiesAsync() {
            return base.Channel.VersiesAsync();
        }
        
        public int DiagnoseOmschrijvingContainsNumber(string searchString) {
            return base.Channel.DiagnoseOmschrijvingContainsNumber(searchString);
        }
        
        public System.Threading.Tasks.Task<int> DiagnoseOmschrijvingContainsNumberAsync(string searchString) {
            return base.Channel.DiagnoseOmschrijvingContainsNumberAsync(searchString);
        }
        
        public RCS.DIS.Presenter.RetrieveService.ServiceReference.Diagnose[] DiagnoseOmschrijvingContainsEntities(string searchString) {
            return base.Channel.DiagnoseOmschrijvingContainsEntities(searchString);
        }
        
        public System.Threading.Tasks.Task<RCS.DIS.Presenter.RetrieveService.ServiceReference.Diagnose[]> DiagnoseOmschrijvingContainsEntitiesAsync(string searchString) {
            return base.Channel.DiagnoseOmschrijvingContainsEntitiesAsync(searchString);
        }
        
        public int SpecialismeOmschrijvingContainsNumber(string searchString) {
            return base.Channel.SpecialismeOmschrijvingContainsNumber(searchString);
        }
        
        public System.Threading.Tasks.Task<int> SpecialismeOmschrijvingContainsNumberAsync(string searchString) {
            return base.Channel.SpecialismeOmschrijvingContainsNumberAsync(searchString);
        }
        
        public RCS.DIS.Presenter.RetrieveService.ServiceReference.Specialisme[] SpecialismeOmschrijvingContainsEntities(string searchString) {
            return base.Channel.SpecialismeOmschrijvingContainsEntities(searchString);
        }
        
        public System.Threading.Tasks.Task<RCS.DIS.Presenter.RetrieveService.ServiceReference.Specialisme[]> SpecialismeOmschrijvingContainsEntitiesAsync(string searchString) {
            return base.Channel.SpecialismeOmschrijvingContainsEntitiesAsync(searchString);
        }
        
        public int ZorgactiviteitOmschrijvingContainsNumber(string searchString) {
            return base.Channel.ZorgactiviteitOmschrijvingContainsNumber(searchString);
        }
        
        public System.Threading.Tasks.Task<int> ZorgactiviteitOmschrijvingContainsNumberAsync(string searchString) {
            return base.Channel.ZorgactiviteitOmschrijvingContainsNumberAsync(searchString);
        }
        
        public RCS.DIS.Presenter.RetrieveService.ServiceReference.Zorgactiviteit[] ZorgactiviteitOmschrijvingContainsEntities(string searchString) {
            return base.Channel.ZorgactiviteitOmschrijvingContainsEntities(searchString);
        }
        
        public System.Threading.Tasks.Task<RCS.DIS.Presenter.RetrieveService.ServiceReference.Zorgactiviteit[]> ZorgactiviteitOmschrijvingContainsEntitiesAsync(string searchString) {
            return base.Channel.ZorgactiviteitOmschrijvingContainsEntitiesAsync(searchString);
        }
        
        public int ZorgproductOmschrijvingContainsNumber(string searchString) {
            return base.Channel.ZorgproductOmschrijvingContainsNumber(searchString);
        }
        
        public System.Threading.Tasks.Task<int> ZorgproductOmschrijvingContainsNumberAsync(string searchString) {
            return base.Channel.ZorgproductOmschrijvingContainsNumberAsync(searchString);
        }
        
        public RCS.DIS.Presenter.RetrieveService.ServiceReference.Zorgproduct[] ZorgproductOmschrijvingContainsEntities(string searchString) {
            return base.Channel.ZorgproductOmschrijvingContainsEntities(searchString);
        }
        
        public System.Threading.Tasks.Task<RCS.DIS.Presenter.RetrieveService.ServiceReference.Zorgproduct[]> ZorgproductOmschrijvingContainsEntitiesAsync(string searchString) {
            return base.Channel.ZorgproductOmschrijvingContainsEntitiesAsync(searchString);
        }
        
        public int DbcOverzichtNumber(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string versie) {
            return base.Channel.DbcOverzichtNumber(jaar, specialismeCode, diagnoseCode, zorgproductCode, versie);
        }
        
        public System.Threading.Tasks.Task<int> DbcOverzichtNumberAsync(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string versie) {
            return base.Channel.DbcOverzichtNumberAsync(jaar, specialismeCode, diagnoseCode, zorgproductCode, versie);
        }
        
        public RCS.DIS.Presenter.RetrieveService.ServiceReference.DbcOverzicht[] DbcOverzichtEntities(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string versie) {
            return base.Channel.DbcOverzichtEntities(jaar, specialismeCode, diagnoseCode, zorgproductCode, versie);
        }
        
        public System.Threading.Tasks.Task<RCS.DIS.Presenter.RetrieveService.ServiceReference.DbcOverzicht[]> DbcOverzichtEntitiesAsync(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string versie) {
            return base.Channel.DbcOverzichtEntitiesAsync(jaar, specialismeCode, diagnoseCode, zorgproductCode, versie);
        }
        
        public int DbcProfielNumber(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string zorgactiviteitCode, string versie) {
            return base.Channel.DbcProfielNumber(jaar, specialismeCode, diagnoseCode, zorgproductCode, zorgactiviteitCode, versie);
        }
        
        public System.Threading.Tasks.Task<int> DbcProfielNumberAsync(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string zorgactiviteitCode, string versie) {
            return base.Channel.DbcProfielNumberAsync(jaar, specialismeCode, diagnoseCode, zorgproductCode, zorgactiviteitCode, versie);
        }
        
        public RCS.DIS.Presenter.RetrieveService.ServiceReference.DbcProfiel[] DbcProfielEntities(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string zorgactiviteitCode, string versie) {
            return base.Channel.DbcProfielEntities(jaar, specialismeCode, diagnoseCode, zorgproductCode, zorgactiviteitCode, versie);
        }
        
        public System.Threading.Tasks.Task<RCS.DIS.Presenter.RetrieveService.ServiceReference.DbcProfiel[]> DbcProfielEntitiesAsync(int jaar, string specialismeCode, string diagnoseCode, int zorgproductCode, string zorgactiviteitCode, string versie) {
            return base.Channel.DbcProfielEntitiesAsync(jaar, specialismeCode, diagnoseCode, zorgproductCode, zorgactiviteitCode, versie);
        }
    }
}
